name: 'Slack Notify'
description: 'slack notify'
inputs:
  channel-id:  
    description: 'slack channel id'
    required: true
    default: ''
  color:
    description: 'color'
    required: true
    default: '#CB2431'
  slack_bot_secret:
    description: 'slack bot secret'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.channel-id }}.
      shell: bash
