name: 'Slack Notify'
description: 'slack notify'
inputs:
  channel-id:  
    description: 'slack channel id'
    required: true
    default: ''
  color:
    description: 'color'
    required: true
    default: '#CB2431'
  slack_bot_token:
    description: 'slack bot secret'
    required: true
    default: ''
  notify_user:
    description: 'user to notify'
    required: true
    default: ''
  workflow_name:
    description: 'workflow name'
    required: false
    default: 'workflow'

runs:
  using: "composite"
  steps:
    - name: set notify user
      shell: bash
      run: | 
        github_id=${{ github.event.pull_request.user.login || github.event.sender.login || github.actor }}
        echo github_id, $github_id
        declare -A users=(["Xuyuchao-juice"]="U084N5R9C9J" ["zxh326"]="U06FKC1S5EU" ["YunhuiChen"]="U06KEM1R4P5" ["simpleqin"]="U09NR61T3BK" ["lynus"]="U09MA9JD9SR" ["lesterMing"]="U08MAV71F4Z" ["jinying-liu"]="U08RW7ZCS2C" ["jiefenghuang"]="U06CFME6N8H" ["CodingPoeta"]="U05EUMHUUDV" ["chenjie4255"]="U02LVG3CHMM" ["anysql"]="U081MR17HKK" ["winglq"]="U07QUA670P8" ["zhoucheng361"]="U035KAH1UV6" ["davies"]="U5RCBSN2C" ["SandyXSD"]="U01UPCZMK99" ["tangyoupeng"]="UK04TUV0C" ["zhijian-pro"]="U02J2DL3CUA" )
        slack_id="${users["$github_id"]}"
        echo slack_id: $slack_id
        echo "slack_id=$slack_id" >> $GITHUB_ENV
        
    - name: send slack notification
      if: ${{github.event_name != 'workflow_dispatch'}} 
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: "${{inputs.channel-id}}"
        payload: |
          {
            "text": "<@${{env.slack_id}}> CI ${{inputs.workflow_name}} ${{ job.status }} on ${{ github.event_name }}",
            "attachments": [
              {
                "pretext":"<@${{env.slack_id}}> CI ${{inputs.workflow_name}} ${{ job.status }} on ${{ github.event_name }}",
                "mrkdwn_in":["text"],
                "author_name":"${{ github.event.pull_request.user.login || github.event.sender.login || github.actor }}",
                "author_link":"${{ github.event.pull_request.user.html_url || github.event.sender.html_url}}",
                "author_icon":"${{ github.event.pull_request.user.avatar_url || github.event.sender.avatar_url }}",
                "title":"${{ github.event.pull_request.title || github.event.head_commit.message }}",
                "text":"https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                "color":"${{inputs.color}}"
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{inputs.slack_bot_token}}
